[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
readme = "README.md"
repository = "https://github.com/japaric/cortex-m"
version = "0.5.8"

[dependencies]
aligned = "0.2.0"
bare-metal = "0.2.0"
volatile-register = "0.2.0"

[dependencies.klee]
path = ".."

[features]
cm7-r0p1 = []
const-fn = ["bare-metal/const-fn"]
inline-asm = []
klee_analysis = []
